
apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJd01EY3hNVEF4TXpZeE1Gb1hEVE13TURjd09UQXhNell4TUZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTmxZCjRQT0dVbGpVSERLSVBqT09XRytMLzFCRGZqK3pRRElKRnNiMW9NT1NtY29xYjlIWW9hTDdmWjRFR1gwODYzdGEKSHRFOEtKVmUvaThlS3pIbHFGNlA5bCsrVnFVTUJGeVNwM0VpeEVQMDY2YllrVzB4TDRjMjBXUUJXcmxqWmhnKwpoM2RMZ1IzbXhKTG9CL1FudXlUN1gvdzJYMUJidDA5YmhNVnd6M0VMOFdqWXQySGZVdDVVaDErNlZxaWRBM1VkClBTREdFcWFraHJEMVFMMHo5QkJEQjVDNVlBQStESmZ2TGpXK05ySkxDS0c1SjlBQThUWlhzU0k5RE5sTjFSNUYKajM3Q25FV2hxdVlkanErNG81U1Z4OG54NEQ4MXozQU5KY3luQVJ2YnpmRVlrYVlLOUxNSzNwWVg1RjVmYytjQQpnRnQwT1NOOTY1bWxxYzRoTUpjQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFDZTRXL21JR0FPTEYxWCtsNWhmOE9HTjg5TXYKbFU1blFoUEZncGFuUlhmN0NoUTNGWCtnUFdPbzdYOWZzYTJFS2JIaitMVGprVUhhdWZBTm5YdGJQNHgveEdzZwpwVmc3ZUpaRkdGT3RTNkEvWHRxazkwdytOVXgwbGJrYUJFZko3dzRhS0UyRGNGbmtZUkppT2ZnbTBGTWFGVmNBClhoWC9aWFpYTU5qNXJRalduN0NDamxwNUNBdmJaR3JoNUZacW5rNS9DWW1Nc0ZRdzVuVXNwckpnWFJHcDRzK1AKbEFEbGlYUVZjVFAwQVoxcFo0bHRDclpQK295cC9uSWpocyt4OXAwc3RMS1M2YVJzYThCbnVRTDEwQnRRVDlqTQpBaUhKWks1NnVlenZpem9Gak9aNUQ0VU1aNkFpY0NQTGxHL3Y2LytLQTVXV2dGQ1BPWVBBYk9sa2Flaz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://c5a3b6a8-b4b8-4692-833c-cce0d6f820c7.us-east-2.linodelke.net:443
  name: lke7373

users:
- name: lke7373-admin
  user:
    as-user-extra: {}
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IlFvU0h0dmlhMHc0UThkelhRa09nSEpaWTJoNXJreWdOVUVNbVNub3JDZUUifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJsa2UtYWRtaW4tdG9rZW4tZzVmNGYiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibGtlLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiMGVkOGY5YTgtYWYxMC00MjhmLWJmYWItYzVhMGRlMTM5ODNkIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmxrZS1hZG1pbiJ9.TjqW73P9pWroIdWH1SAtm8ABgbGSYSMzQ4RoCKtabdm5QtiT2L04FKmklSvyyFVaPtfhSwVLlDqYqoC304qlQ1DrFFwp5rlHGrNY4geYOKd9lJKVLL-frLma5bdfuUQ3cjdUGRbxYrSTXrbeLr2mSJ-G0Bjv2_D2HeG459lR974MGJgpwrQlwwENmVgrnDAlA08_RxGY-UbpqCnhkhIVcfds4kEPgI_znI7SBeFwge-RncbMeyFZ7-D_IfvddlonFGl9f5A0iETw0gpseezpwZiiNaXOrjZUOAClqY5XAJeGV4POB8pDXOjK4PBXmXKjgSiNbvfllWxpNB6YuxfgEw

contexts:
- context:
    cluster: lke7373
    namespace: default
    user: lke7373-admin
  name: lke7373-ctx

current-context: lke7373-ctx
